<a href="https://colab.research.google.com/github/krasnovaov81-coder/Case_DZ_Netology/blob/main/%D0%90%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7_%D0%BE%D0%B1%D1%80%D0%B0%D1%89%D0%B5%D0%BD%D0%B8%D0%B8%CC%86_%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%BE%D0%B2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Анализ обращений клиентов

## Описание задания

Вы — аналитик в компании, которая продаёт электронику и программное обеспечение.
Компания собрала обращения клиентов в службу поддержки и хочет проанализировать
качество обслуживания.

Вы будете работать с **реальным датасетом** «Customer Support Ticket Dataset» с Kaggle.

**Источник данных:** [Customer Support Ticket Dataset](https://www.kaggle.com/datasets/suraj520/customer-support-ticket-dataset)

## Цели задания
- Освоить фильтрацию DataFrame по условиям
- Научиться создавать вычисляемые столбцы
- Освоить подсчёт средних значений и сортировку
- Научиться формулировать аналитические выводы на основе данных

## Шаг 0: Загрузка данных

Загрузите датасет с Kaggle.

In [ ]:
import kagglehub
import pandas as pd
import io

# Загружаем датасет Customer Support Tickets с Kaggle
path = kagglehub.dataset_download("suraj520/customer-support-ticket-dataset")
df = pd.read_csv(path + "/customer_support_tickets.csv")

print(f"Размер таблицы: {df.shape}")
display(df.head(3))

Using Colab cache for faster access to the 'customer-support-ticket-dataset' dataset.
Размер таблицы: (8469, 17)

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0

---
## Задание 1: Первичный осмотр данных

Прежде чем анализировать обращения, нужно понять структуру данных.

**Задачи:**
1. Выведите размер таблицы (атрибут `.shape`)
2. Выведите первые 5 строк с помощью `.head()`
3. Выведите общую информацию с помощью `.info()`
4. Выведите статистику числовых столбцов с помощью `.describe()`
5. Посмотрите на уникальные значения в столбцах `Ticket Priority` и `Ticket Channel` (используйте `.value_counts()`)

**Вопрос:**
Сколько всего обращений в наборе данных? Какие приоритеты существуют?
 Какие каналы связи используются?

In [ ]:
# Ваше решение:
# 1. Выведите размер таблицы (атрибут .shape)
print("Размер таблицы (строки, столбцы):")
print(df.shape)
print("-" * 50)

Размер таблицы (строки, столбцы):
(8469, 17)
--------------------------------------------------

In [ ]:
# 2. Выведите первые 5 строк с помощью .head()
print("Первые 5 строк данных:")
# Используем to_string(), чтобы таблица не обрезалась по ширине в выводе Colab
print(df.head().to_string())
print("-" * 50)

Первые 5 строк данных:
   Ticket ID        Customer Name              Customer Email  Customer Age Customer Gender Product Purchased Date of Purchase      Ticket Type            Ticket Subject                                                                                                                                                                                                                                                                                                                                Ticket Description              Ticket Status                                     Resolution Ticket Priority Ticket Channel  First Response Time   Time to Resolution  Customer Satisfaction Rating
0          1        Marisa Obrien  carrollallison@example.com            32           Other        GoPro Hero       2021-03-22  Technical issue             Product setup                                                I'm having an issue with the {product_purchased}. Please assist.\n\nYour billing zip code is: 71701.\n\nWe appreciate that you have requested a website address.\n\nPlease double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.  Pending Customer Response                                            NaN        Critical   Social media  2023-06-01 12:15:36                  NaN                           NaN
1          2         Jessica Rios    clarkeashley@example.com            42          Female       LG Smart TV       2021-05-22  Technical issue  Peripheral compatibility                                                  I'm having an issue with the {product_purchased}. Please assist.\n\nIf you need to change an existing product.\n\nI'm having an issue with the {product_purchased}. Please assist.\n\nIf The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.  Pending Customer Response                                            NaN        Critical           Chat  2023-06-01 16:45:38                  NaN                           NaN
2          3  Christopher Robbins   gonzalestracy@example.com            48           Other          Dell XPS       2020-07-14  Technical issue           Network problem                                                             I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond.\n\n1.8.3 I really I'm using the original charger that came with my {product_purchased}, but it's not charging properly.                     Closed   Case maybe show recently my computer follow.             Low   Social media  2023-06-01 11:14:38  2023-06-01 18:05:38                           3.0
3          4     Christina Dillon    bradleyolson@example.org            27          Female  Microsoft Office       2020-11-13  Billing inquiry            Account access                                                                          I'm having an issue with the {product_purchased}. Please assist.\n\nIf you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved.                     Closed  Try capital clearly never color toward story.             Low   Social media  2023-06-01 07:29:40  2023-06-01 01:57:40                           3.0
4          5    Alexander Carroll     bradleymark@example.com            67          Female  Autodesk AutoCAD       2020-02-04  Billing inquiry                 Data loss  I'm having an issue with the {product_purchased}. Please assist.\n\n\nNote: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my {product_purchased}. It used to last much longer.                     Closed                    West decision evidence bit.             Low          Email  2023-06-01 00:12:42  2023-06-01 19:53:42                           1.0
--------------------------------------------------

In [ ]:
# 3. Выведите общую информацию с помощью .info()
print("Общая информация о DataFrame:")
buffer = io.StringIO()
df.info(buf=buffer)
print(buffer.getvalue())
print("-" * 50)

Общая информация о DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8469 entries, 0 to 8468
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ticket ID                     8469 non-null   int64
 1   Customer Name                 8469 non-null   object
 2   Customer Email                8469 non-null   object
 3   Customer Age                  8469 non-null   int64
 4   Customer Gender               8469 non-null   object
 5   Product Purchased             8469 non-null   object
 6   Date of Purchase              8469 non-null   object
 7   Ticket Type                   8469 non-null   object
 8   Ticket Subject                8469 non-null   object
 9   Ticket Description            8469 non-null   object
 10  Ticket Status                 8469 non-null   object
 11  Resolution                    2769 non-null   object
 12  Ticket Priority               8469 non-null   object
 13  Ticket Channel                8469 non-null   object
 14  First Response Time           5650 non-null   object
 15  Time to Resolution            2769 non-null   object
 16  Customer Satisfaction Rating  2769 non-null   float64
dtypes: float64(1), int64(2), object(14)
memory usage: 1.1+ MB

--------------------------------------------------

In [ ]:
# 4. Выведите статистику числовых столбцов с помощью .describe()
print("Статистика по числовым столбцам:")
# include=[int, float] гарантирует, что мы увидим данные только для чисел
print(df.describe(include=[int, float]).to_string())
print("-" * 50)

Статистика по числовым столбцам:
         Ticket ID  Customer Age  Customer Satisfaction Rating
count  8469.000000   8469.000000                   2769.000000
mean   4235.000000     44.026804                      2.991333
std    2444.934048     15.296112                      1.407016
min       1.000000     18.000000                      1.000000
25%    2118.000000     31.000000                      2.000000
50%    4235.000000     44.000000                      3.000000
75%    6352.000000     57.000000                      4.000000
max    8469.000000     70.000000                      5.000000
--------------------------------------------------

In [ ]:
# 5. Посмотрите на уникальные значения в столбцах Ticket Priority и Ticket Channel
print("Распределение приоритетов (Ticket Priority):")
priority_counts = df['Ticket Priority'].value_counts(dropna=False)
print(priority_counts)
print("-" * 50)

print("Распределение каналов связи (Ticket Channel):")
channel_counts = df['Ticket Channel'].value_counts(dropna=False)
print(channel_counts)
print("-" * 50)

# --- Ответы на вопросы из задания ---
total_tickets = df.shape[0]
priorities = priority_counts.index.tolist()
channels = channel_counts.index.tolist()

print("\nИТОГОВЫЕ ОТВЕТЫ НА ВОПРОСЫ ЗАДАНИЯ:")
print(f"1. Всего обращений в наборе данных: {total_tickets}")
print(f"2. Существующие приоритеты ({len(priorities)} шт.): {', '.join(priorities)}")
print(f"3. Каналы связи ({len(channels)} шт.): {', '.join(channels)}")

Распределение приоритетов (Ticket Priority):
Ticket Priority
Medium      2192
Critical    2129
High        2085
Low         2063
Name: count, dtype: int64
--------------------------------------------------
Распределение каналов связи (Ticket Channel):
Ticket Channel
Email           2143
Phone           2132
Social media    2121
Chat            2073
Name: count, dtype: int64
--------------------------------------------------

ИТОГОВЫЕ ОТВЕТЫ НА ВОПРОСЫ ЗАДАНИЯ:
1. Всего обращений в наборе данных: 8469
2. Существующие приоритеты (4 шт.): Medium, Critical, High, Low
3. Каналы связи (4 шт.): Email, Phone, Social media, Chat

---
## Задание 2: Фильтрация данных

Руководитель хочет разобраться в конкретных проблемах.
Он просит отобрать обращения по разным критериям.

**Задачи:**

### 2.1. Проблемные обращения
Отберите все обращения с оценкой удовлетворённости **ниже 3.0**
(столбец `Customer Satisfaction Rating`).
Сохраните результат в переменную `df_low_satisfaction`.
Выведите количество таких обращений.

### 2.2. Критические обращения по конкретных каналах
Отберите обращения с приоритетом **«Critical»**, которые поступили через каналы **«Phone»** или **«Chat»**.
Сохраните результат в переменную `df_critical_phone_chat`.
Выведите результат.

### 2.3. Обращения по конкретным продуктам
Отберите обращения по продуктам **«GoPro Hero»** или **«Dell XPS»**,
где приоритет **«High»** или **«Critical»**.
Сохраните в переменную `df_tech_urgent`.
Выведите только столбцы: `Ticket ID`, `Product Purchased`, `Ticket Priority`, `Ticket Channel`, `Customer Satisfaction Rating`.
Отсортируйте по `Customer Satisfaction Rating` по возрастанию.

In [ ]:
# Ваше решение:
# Решение задания 2.1 — Проблемные обращения
# Отбор обращений с оценкой удовлетворенности ниже 3.0.
# Фильтрация
df_low_satisfaction = df[df['Customer Satisfaction Rating'] < 3.0]

# Сохранение количества
count_low_sat = len(df_low_satisfaction)

print(f"Задание 2.1:")
print(f"Количество обращений с оценкой ниже 3.0: {count_low_sat}")
print("Первые 5 строк проблемных обращений:")
display(df_low_satisfaction.head())

Задание 2.1:
Количество обращений с оценкой ниже 3.0: 1102
Первые 5 строк проблемных обращений:

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0
10,11,Joseph Moreno,mbrown@example.org,48,Male,Nintendo Switch,2021-01-19,Cancellation request,Data loss,I'm having an issue with the {product_purchase...,Closed,Measure tonight surface feel forward.,High,Phone,2023-06-01 17:46:49,2023-05-31 23:51:49,1.0
11,12,Brandon Arnold,davisjohn@example.net,51,Male,Microsoft Xbox Controller,2021-10-24,Product inquiry,Software bug,I'm having an issue with the {product_purchase...,Closed,Measure there house management pick knowledge ...,High,Chat,2023-06-01 12:05:51,2023-06-01 09:27:51,1.0
29,30,Austin George,shericase@example.net,67,Male,Xbox,2020-12-26,Cancellation request,Cancellation request,I'm having an issue with the {product_purchase...,Closed,Firm sort voice above which site arrive.,Medium,Phone,2023-06-01 00:54:17,2023-06-01 18:23:17,1.0
35,36,Joann King,jessica10@example.org,24,Other,GoPro Hero,2020-10-13,Cancellation request,Product recommendation,"I've recently set up my {product_purchased}, b...",Closed,Reach paper ability effort learn.,High,Chat,2023-06-01 07:56:25,2023-06-01 00:14:25,1.0

In [ ]:
# Решение задания 2.2 — Критические обращения через Phone или Chat
# Использование метода .isin() для проверки принадлежности к списку каналов.
mask_priority = df['Ticket Priority'] == 'Critical'
mask_channel = df['Ticket Channel'].isin(['Phone', 'Chat'])

df_critical_phone_chat = df[mask_priority & mask_channel]

print("\nЗадание 2.2:")
print(f"Найдено критических обращений через Phone/Chat: {len(df_critical_phone_chat)}")
display(df_critical_phone_chat)

Задание 2.2:
Найдено критических обращений через Phone/Chat: 1030

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
9,10,William Dawson,clopez@example.com,27,Male,Dyson Vacuum Cleaner,2020-03-06,Refund request,Payment issue,My {product_purchased} is making strange noise...,Pending Customer Response,NaN,Critical,Phone,2023-06-01 09:25:48,NaN,NaN
16,17,Julia Salazar,watkinsbarbara@example.com,63,Other,Xbox,2021-10-13,Product inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Seek evidence book collection catch.,Critical,Chat,2023-06-01 19:46:59,2023-06-01 15:58:59,4.0
28,29,Christine Wang,garciastacy@example.com,30,Other,Fitbit Charge,2020-06-10,Technical issue,Product recommendation,I'm having an issue with the {product_purchase...,Closed,Soldier we such inside.,Critical,Phone,2023-05-31 23:17:17,2023-06-01 06:03:17,5.0
38,39,Kevin Ingram,victor62@example.net,19,Male,Google Pixel,2021-09-10,Technical issue,Account access,I'm having an issue with the {product_purchase...,Closed,North second between this cell opportunity mov...,Critical,Phone,2023-06-01 18:45:30,2023-05-31 21:53:30,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8432,8433,Yolanda Miller,robertramirez@example.com,70,Male,Nintendo Switch,2020-01-22,Billing inquiry,Network problem,There seems to be a glitch in the {product_pur...,Closed,Off budget pull nearly.,Critical,Chat,2023-06-01 07:25:38,2023-06-01 15:47:38,3.0
8438,8439,Andrea Bates,kristinasherman@example.com,19,Other,Garmin Forerunner,2020-12-18,Refund request,Cancellation request,I've noticed a software bug in the {product_pu...,Pending Customer Response,NaN,Critical,Phone,2023-06-01 22:27:46,NaN,NaN
8445,8446,Debbie Buchanan,martinnicholas@example.net,66,Male,Nintendo Switch Pro Controller,2021-02-16,Refund request,Payment issue,I'm having an issue with the {product_purchase...,Open,NaN,Critical,Chat,NaN,NaN,NaN
8446,8447,Steven Brown,umoore@example.org,19,Other,LG OLED,2020-03-14,Billing inquiry,Installation support,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 09:42:57,NaN,NaN
8452,8453,Craig Forbes,jessica60@example.org,62,Female,MacBook Pro,2020-03-29,Refund request,Display issue,I'm having an issue with the {product_purchase...,Closed,Interesting show must successful.,Critical,Phone,2023-06-01 14:14:05,2023-06-01 05:47:05,3.0

In [ ]:
# Решение задания 2.3 — Обращения по GoPro Hero / Dell XPS с высоким приоритетом
# Сложная фильтрация по двум продуктам и двум приоритетам, выборка конкретных колонок и сортировка.
# Условия фильтрации
mask_products = df['Product Purchased'].isin(['GoPro Hero', 'Dell XPS'])
mask_urgent = df['Ticket Priority'].isin(['High', 'Critical'])

# Применение фильтров и выбор нужных столбцов
columns_to_show = [
    'Ticket ID',
    'Product Purchased',
    'Ticket Priority',
    'Ticket Channel',
    'Customer Satisfaction Rating'
]

df_tech_urgent = df[mask_products & mask_urgent][columns_to_show]

# Сортировка по оценке (по возрастанию). NaN (пустые значения) окажутся в конце списка.
df_tech_urgent_sorted = df_tech_urgent.sort_values(
    by='Customer Satisfaction Rating',
    ascending=True,
    na_position='last' # явно указываем ставить пустые оценки вниз
)

print("\nЗадание 2.3:")
print("Обращения по GoPro Hero/Dell XPS (Priority: High/Critical), отсортированные по оценке:")
display(df_tech_urgent_sorted)

Задание 2.3:
Обращения по GoPro Hero/Dell XPS (Priority: High/Critical), отсортированные по оценке:

,Ticket ID,Product Purchased,Ticket Priority,Ticket Channel,Customer Satisfaction Rating
35,36,GoPro Hero,High,Chat,1.0
373,374,GoPro Hero,Critical,Phone,1.0
1618,1619,Dell XPS,Critical,Chat,1.0
1568,1569,GoPro Hero,Critical,Social media,1.0
1378,1379,GoPro Hero,High,Email,1.0
...,...,...,...,...,...
8277,8278,Dell XPS,High,Chat,NaN
8305,8306,GoPro Hero,High,Phone,NaN
8378,8379,Dell XPS,Critical,Social media,NaN
8442,8443,GoPro Hero,High,Social media,NaN
8447,8448,GoPro Hero,Critical,Email,NaN

---
## Задание 3: Вычисляемые столбцы

Для оценки качества работы службы поддержки нужны дополнительные показатели.

**Задача:**

### 3.1. Признак низкой удовлетворённости
Создайте новый столбец `is_low_satisfaction`, который равен `True`,
если `Customer Satisfaction Rating` меньше 3.0, и `False` в противном случае.

### 3.2. Категория возраста клиента
Создайте столбец `age_group` по правилу:
- Если `Customer Age` < 30 → значение **«Молодой»**
- Если `Customer Age` < 50 → значение **«Средний»**
- Если `Customer Age` >= 50 → значение **«Старший»**

In [ ]:
# Ваше решение:
# --- Задание 3.1. Признак низкой удовлетворённости ---
# Создаем булев столбец.
# Если рейтинг меньше 3.0 -> True, иначе False. Для NaN результат будет False.
df['is_low_satisfaction'] = df['Customer Satisfaction Rating'] < 3.0

In [ ]:
# --- Задание 3.2. Категория возраста клиента ---
# Используем pd.cut для автоматического разбиения на интервалы
bins = [0, 30, 50, float('inf')]
labels = ['Молодой', 'Средний', 'Старший']

# Параметр right=False делает интервалы вида [от, до), то есть 30 попадет в "Средний", а не "Молодой"
df['age_group'] = pd.cut(
    df['Customer Age'],
    bins=bins,
    labels=labels,
    right=False
)

# --- Вывод результатов для проверки ---
print("=== РЕЗУЛЬТАТЫ ЗАДАНИЯ 3 ===\n")

print("--- 3.1. Столбец is_low_satisfaction (первые 10 строк) ---")
display(df[['Ticket ID', 'Customer Satisfaction Rating', 'is_low_satisfaction']].head(10))

print("\n--- 3.2. Столбец age_group (первые 10 строк) ---")
display(df[['Ticket ID', 'Customer Age', 'age_group']].head(10))

print("\n--- Статистика по новым признакам ---")
print(f"Количество клиентов с низкой оценкой (< 3.0): {df['is_low_satisfaction'].sum()}")
print("Распределение по возрастным группам:")
print(df['age_group'].value_counts(dropna=False))

=== РЕЗУЛЬТАТЫ ЗАДАНИЯ 3 ===

--- 3.1. Столбец is_low_satisfaction (первые 10 строк) ---

   Ticket ID  Customer Satisfaction Rating  is_low_satisfaction
0          1                           NaN                False
1          2                           NaN                False
2          3                           3.0                False
3          4                           3.0                False
4          5                           1.0                 True
5          6                           NaN                False
6          7                           NaN                False
7          8                           NaN                False
8          9                           NaN                False
9         10                           NaN                False

--- 3.2. Столбец age_group (первые 10 строк) ---

   Ticket ID  Customer Age age_group
0          1            32   Средний
1          2            42   Средний
2          3            48   Средний
3          4            27   Молодой
4          5            67   Старший
5          6            53   Старший
6          7            24   Молодой
7          8            23   Молодой
8          9            60   Старший
9         10            27   Молодой

--- Статистика по новым признакам ---
Количество клиентов с низкой оценкой (< 3.0): 1102
Распределение по возрастным группам:
age_group
Старший    3400
Средний    3141
Молодой    1928
Name: count, dtype: int64

---
## Задание 4: Агрегация и сортировка

Для отчёта руководству нужны конкретные цифры.

**Задача:**

### 4.1. Средние показатели
Рассчитайте и выведите:
- Среднюю оценку удовлетворённости по всем данным
- Среднюю оценку удовлетворённости для обращений с приоритетом «Critical»
- Среднюю оценку удовлетворённости для обращений с приоритетом «Low»
- Средний возраст клиента по всем данным

### 4.2. Сравнение по каналам
Рассчитайте среднюю оценку удовлетворённости отдельно для каждого канала:
- «Email», «Phone», «Social media», «Chat»
Выведите результаты в читаемом виде.

### 4.3. Топ самых проблемных продуктов
С помощью `.value_counts()` определите **топ-5** продуктов (`Product Purchased`),
на которые поступило больше всего обращений.
Выведите результат.

In [ ]:
# Ваше решение:
# --- Задание 4.1. Средние показатели ---
overall_sat_mean = df['Customer Satisfaction Rating'].mean()
critical_sat_mean = df[df['Ticket Priority'] == 'Critical']['Customer Satisfaction Rating'].mean()
low_sat_mean = df[df['Ticket Priority'] == 'Low']['Customer Satisfaction Rating'].mean()
overall_age_mean = df['Customer Age'].mean()

print("=== ЗАДАНИЕ 4.1: Средние показатели ===")
print(f"Средняя оценка удовлетворённости (все данные): {overall_sat_mean:.2f}")
print(f"Средняя оценка удовлетворённости (Priority: Critical): {critical_sat_mean:.2f}")
print(f"Средняя оценка удовлетворённости (Priority: Low): {low_sat_mean:.2f}")
print(f"Средний возраст клиента (все данные): {overall_age_mean:.1f} лет")
print("-" * 50)

=== ЗАДАНИЕ 4.1: Средние показатели ===
Средняя оценка удовлетворённости (все данные): 2.99
Средняя оценка удовлетворённости (Priority: Critical): 2.96
Средняя оценка удовлетворённости (Priority: Low): 3.05
Средний возраст клиента (все данные): 44.0 лет
--------------------------------------------------

In [ ]:
# --- Задание 4.2. Сравнение по каналам ---
satisfaction_by_channel = df.groupby('Ticket Channel')['Customer Satisfaction Rating'].mean().sort_values(ascending=False)

print("=== ЗАДАНИЕ 4.2: Средняя оценка по каналам ===")
print(satisfaction_by_channel.round(2).to_string())
print("-" * 50)

# --- Задание 4.3. Топ самых проблемных продуктов ---
top_5_products = df['Product Purchased'].value_counts().head(5)

print("=== ЗАДАНИЕ 4.3: Топ-5 продуктов по количеству обращений ===")
print(top_5_products)
print("-" * 50)

# Дополнительная информация о разнообразии товаров
unique_products_count = df['Product Purchased'].nunique()
print(f"Всего уникальных продуктов в базе: {unique_products_count}")

=== ЗАДАНИЕ 4.2: Средняя оценка по каналам ===
Ticket Channel
Chat            3.08
Social media    2.97
Email           2.96
Phone           2.95
--------------------------------------------------
=== ЗАДАНИЕ 4.3: Топ-5 продуктов по количеству обращений ===
Product Purchased
Canon EOS             240
GoPro Hero            228
Nest Thermostat       225
Amazon Echo           221
Philips Hue Lights    221
Name: count, dtype: int64
--------------------------------------------------
Всего уникальных продуктов в базе: 42

---
## Задание 5: Аналитический вывод

Цифры — это инструмент, а не результат. Руководству
нужны понятные выводы и рекомендации.

**Задача:**
На основе проведённого анализа напишите краткий аналитический отчёт (3-4 предложения).

В отчёте отразите:
1. Какой продукт вызывает больше всего обращений? (используйте результаты задания 4.3)
2. Есть ли разница в удовлетворённости между разными каналами связи? (задание 4.2)
3. Как приоритет обращения связан с оценкой удовлетворённости? (задание 4.1)
4. Сформулируйте одну рекомендацию для руководителя службы поддержки.

Напишите вывод в ячейке ниже в виде текста (можно использовать print).

In [ ]:
# Ваше решение:
print("АНАЛИТИЧЕСКИЙ ОТЧЕТ ДЛЯ РУКОВОДСТВА\n")
print("Лидером по количеству обращений является продукт «Canon EOS», что указывает на системные проблемы в его эксплуатации или документации.")
print("Разница в удовлетворенности между каналами связи ощутима: оценки варьируются от 3.08 (Chat) до 2.95 (Phone). Наименее эффективный канал — телефонная линия, в то время как текстовые каналы показывают более высокий результат.")
print("Связь между приоритетом и оценкой нелинейна: вопреки ожиданиям, средняя оценка по критическим тикетам (2.96) ниже, чем по низкоприоритетным (3.05), так как при решении срочных проблем клиенты предъявляют более жесткие требования к скорости и качеству.")
print("\nРЕКОМЕНДАЦИЯ:")
print("Необходимо внедрить скрипт быстрой диагностики для телефонной линии и пересмотреть регламент обработки заявок с приоритетом «Critical», добавив обязательный шаг контрольного звонка через 24 часа после закрытия тикета.")

АНАЛИТИЧЕСКИЙ ОТЧЕТ ДЛЯ РУКОВОДСТВА

Лидером по количеству обращений является продукт «Canon EOS», что указывает на системные проблемы в его эксплуатации или документации.
Разница в удовлетворенности между каналами связи ощутима: оценки варьируются от 3.08 (Chat) до 2.95 (Phone). Наименее эффективный канал — телефонная линия, в то время как текстовые каналы показывают более высокий результат.
Связь между приоритетом и оценкой нелинейна: вопреки ожиданиям, средняя оценка по критическим тикетам (2.96) ниже, чем по низкоприоритетным (3.05), так как при решении срочных проблем клиенты предъявляют более жесткие требования к скорости и качеству.

РЕКОМЕНДАЦИЯ:
Необходимо внедрить скрипт быстрой диагностики для телефонной линии и пересмотреть регламент обработки заявок с приоритетом «Critical», добавив обязательный шаг контрольного звонка через 24 часа после закрытия тикета.

---
### ⭐ Задание 6: Проблемный продукт (задание со звёздочкой)

*Это задание не является обязательным, но поможет вам лучше освоить материал.*

Руководитель подозревает, что один из продуктов
генерирует больше всего жалоб с низкими оценками. Нужно проверить эту гипотезу.

**Задача:**
1. Определите продукт, на который поступило **больше всего** обращений с оценкой ниже 3.0.
2. Посчитайте среднюю оценку удовлетворённости для этого продукта.
3. Сравните её со средней оценкой по всем продуктам.
4. Сделайте вывод — подтверждается ли гипотеза руководителя?

In [ ]:
# Ваше решение:
# --- Шаг 1: Определение проблемного продукта ---
# Фильтруем только обращения с низкой оценкой (< 3.0)
df_low = df[df['Customer Satisfaction Rating'] < 3.0]

# Находим продукт-лидер по количеству таких обращений
problem_product = df_low['Product Purchased'].value_counts().idxmax()
problem_product_count = df_low['Product Purchased'].value_counts().max()

# --- Шаг 2: Расчет средних оценок ---
# Средняя оценка для этого конкретного продукта (по ВСЕМ его тикетам)
avg_sat_problem_product = df[df['Product Purchased'] == problem_product]['Customer Satisfaction Rating'].mean()

# Средняя оценка по всем продуктам в базе (базовая линия)
overall_avg_sat = df['Customer Satisfaction Rating'].mean()

# --- Шаг 3: Проверка гипотезы ---
is_hypothesis_confirmed = avg_sat_problem_product < overall_avg_sat

# --- Вывод результатов ---
print(f"1. Продукт с наибольшим количеством жалоб (< 3.0):")
print(f"   -> {problem_product} ({problem_product_count} обращений)")
print("-" * 50)

print(f"2. Средняя оценка удовлетворённости для «{problem_product}» (по всем его тикетам):")
print(f"   -> {avg_sat_problem_product:.2f}")
print("-" * 50)

print(f"3. Средняя оценка удовлетворённости по всем продуктам (базовая линия):")
print(f"   -> {overall_avg_sat:.2f}")
print("-" * 50)

print("4. Вывод:")
if is_hypothesis_confirmed:
    print(f"   Гипотеза руководителя ПОДТВЕРЖДАЕТСЯ. Средняя оценка продукта «{problem_product}» ({avg_sat_problem_product:.2f}) ниже общей средней по базе ({overall_avg_sat:.2f}).")
    print("   Этот продукт не только генерирует больше всего негативных отзывов, но и имеет системно низкое качество клиентского опыта.")
else:
    print(f"   Гипотеза руководителя НЕ ПОДТВЕРЖДАЕТСЯ. Несмотря на большое количество жалоб, средняя оценка «{problem_product}» ({avg_sat_problem_product:.2f}) не ниже средней по базе ({overall_avg_sat:.2f}).")
    print("   Проблема, скорее всего, заключается в массовости продукта, а не в его качестве.")

1. Продукт с наибольшим количеством жалоб (< 3.0):
   -> Sony Xperia (37 обращений)
--------------------------------------------------
2. Средняя оценка удовлетворённости для «Sony Xperia» (по всем его тикетам):
   -> 2.69
--------------------------------------------------
3. Средняя оценка удовлетворённости по всем продуктам (базовая линия):
   -> 2.99
--------------------------------------------------
4. Вывод:
   Гипотеза руководителя ПОДТВЕРЖДАЕТСЯ. Средняя оценка продукта «Sony Xperia» (2.69) ниже общей средней по базе (2.99).
   Этот продукт не только генерирует больше всего негативных отзывов, но и имеет системно низкое качество клиентского опыта.