<a href="https://colab.research.google.com/github/krasnovaov81-coder/Case_DZ_Netology/blob/main/%D0%9E%D1%87%D0%B8%D1%81%D1%82%D0%BA%D0%B0_%D0%B8_%D0%BF%D0%BE%D0%B4%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D0%BA%D0%B0_%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Диагностика качества данных**

## **Описание задания**

Вы — аналитик в сети кофеен. Компания ведёт учёт заказов в единой системе, но данные поступают из нескольких источников: кассовые терминалы, мобильное приложение, агрегаторы доставки. Из-за этого в данных регулярно встречаются ошибки.Руководство попросило вас подготовить чистый датасет для построения дашборда продаж. Прежде чем строить графики и считать метрики, данные нужно привести в порядок.

**Описание столбцов:**
- `order_id` — идентификатор заказа (должен быть уникальным)
- `order_date` — дата заказа (строка в формате "YYYY-MM-DD", могут быть некорректные значения)
- `drink` — название напитка- `size` — размер порции (S / M / L)
- `price` — цена заказа (строка, может содержать текст)
- `quantity` — количество порций в заказе
- `payment_method` — способ оплаты (Cash / Card / App)
- `customer_age` — возраст клиента
- `tip` — размер чаевых
- `source` — источник заказа (terminal / app / delivery)

## **Шаг 0. Загрузка данных**
Загрузите [датасет](https://u.netology.ru/backend/uploads/lms/content_assets/file/15093/coffee_orders_dirty.csv) `coffee_orders_dirty.csv`.

In [ ]:
import pandas as pd
df = pd.read_csv("coffee_orders_dirty.csv")
df

,order_id,order_date,drink,size,price,quantity,payment_method,customer_age,tip,source
0,138004,2024-12-04,Mocha,M,396,2,Cash,42.0,46.0,delivery
1,186147,2024-11-02,Cappuccino,M,356,1,Card,35.0,79.0,terminal
2,182196,2024-10-29,Matcha Latte,M,449,1,Cash,47.0,28.0,delivery
3,129183,2024-10-11,Flat White,L,505,1,Card,23.0,14.0,app
4,161660,2024-11-06,Espresso,L,266,3,Cash,40.0,24.0,app
...,...,...,...,...,...,...,...,...,...,...
106245,154887,2024-10-25,Matcha Latte,M,415,3,Cash,38.0,39.0,terminal
106246,176821,2024-11-16,Flat White,M,369,1,Card,16.0,34.0,terminal
106247,203695,2024-10-26,Mocha,M,384,2,Cash,26.0,11.0,delivery
106248,100861,2024-11-20,Americano,L,318,1,Card,46.0,19.0,app
106249,115796,2024-11-15,Latte,L,454,2,Card,51.0,7.0,app

In [ ]:
import pandas as pd

# Загрузка файла из директории Colab
file_path = '/content/coffee_orders_dirty.csv'
df = pd.read_csv(file_path)

# Базовая проверка структуры
print(f"Размер датасета: {df.shape[0]} строк x {df.shape[1]} столбцов")
print("\nПервые 5 строк:")
display(df.head())

print("\nИнформация о данных (типы и пропуски):")
df.info()

print("\nСтатистика по числовым полям:")
display(df.describe(include='number'))

Размер датасета: 106250 строк x 10 столбцов

Первые 5 строк:

,order_id,order_date,drink,size,price,quantity,payment_method,customer_age,tip,source
0,138004,2024-12-04,Mocha,M,396,2,Cash,42.0,46.0,delivery
1,186147,2024-11-02,Cappuccino,M,356,1,Card,35.0,79.0,terminal
2,182196,2024-10-29,Matcha Latte,M,449,1,Cash,47.0,28.0,delivery
3,129183,2024-10-11,Flat White,L,505,1,Card,23.0,14.0,app
4,161660,2024-11-06,Espresso,L,266,3,Cash,40.0,24.0,app

Информация о данных (типы и пропуски):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106250 entries, 0 to 106249
Data columns (total 10 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_id        106250 non-null  int64
 1   order_date      106240 non-null  object
 2   drink           106148 non-null  object
 3   size            106250 non-null  object
 4   price           106230 non-null  object
 5   quantity        106250 non-null  int64
 6   payment_method  106250 non-null  object
 7   customer_age    103710 non-null  float64
 8   tip             105441 non-null  float64
 9   source          106250 non-null  object
dtypes: float64(2), int64(2), object(6)
memory usage: 8.1+ MB

Статистика по числовым полям:

            order_id       quantity   customer_age            tip
count  106250.000000  106250.000000  103710.000000  105441.000000
mean   152509.935247       1.571558      34.799084      30.886704
std     30312.919436       0.729035      11.543089      43.313844
min    100001.000000      -2.000000      -5.000000    -188.000000
25%    126250.250000       1.000000      26.000000       9.000000
50%    152520.500000       1.000000      34.000000      21.000000
75%    178760.750000       2.000000      43.000000      42.000000
max    205000.000000       3.000000     300.000000    1998.000000

## **Задание 1. Первичный осмотр данных**

Прежде чем что-либо исправлять, нужно понять, с чем вы работаете.

**Задачи:**
1. Выведите размер таблицы.
2. Выведите первые 10 строк.
3. Выведите информацию о типах данных и количестве непустых значений, а также определите объём памяти, занимаемой датасетом.
4. Выведите описательную статистику числовых столбцов.
5. Посмотрите на уникальные значения в столбцах `drink`, `size`, `payment_method` и `source`.

**Вопросы (ответьте в ячейке ниже):**
1. Сколько строк и столбцов в датасете?
2. Какие столбцы имеют тип `object`, хотя по смыслу должны быть числовыми или датами?
3. Есть ли в статистике подозрительные значения (например, отрицательные чаевые или аномальный возраст)?

In [ ]:
# Ваше решение:
print("=" * 50)
# Задача 1: Размер таблицы
print("ЗАДАЧА 1: РАЗМЕР ТАБЛИЦЫ")
print(f"Строк: {df.shape[0]}, Столбцов: {df.shape[1]}")
print("=" * 50)

# Задача 2: Первые 10 строк
print("\nЗАДАЧА 2: ПЕРВЫЕ 10 СТРОК ДАТАСЕТА")
display(df.head(10))
print("=" * 50)

# Задача 3: Информация о типах, непустых значениях и памяти
print("\nЗАДАЧА 3: ИНФОРМАЦИЯ О ДАТАСЕТЕ (INFO & MEMORY)")
# Включаем опцию show_counts=True для явного отображения числа непустых значений
df.info(memory_usage='deep', verbose=True, show_counts=True)
mem_mb = df.memory_usage(deep=True).sum() / (1024 ** 2)
print(f"\nОбщий объем памяти датасета: {mem_mb:.2f} МБ")
print("=" * 50)

# Задача 4: Описательная статистика числовых столбцов
print("\nЗАДАЧА 4: ОПИСАТЕЛЬНАЯ СТАТИСТИКА ЧИСЛОВЫХ СТОЛБЦОВ")
# include='number' гарантирует вывод только числовых типов данных
display(df.describe(include='number'))
print("=" * 50)

# Задача 5: Уникальные значения в категориальных столбцах
categorical_cols = ['drink', 'size', 'payment_method', 'source']
for col in categorical_cols:
    print(f"\nУникальные значения в '{col}':")
    # Добавляем .sort_index(), чтобы категории шли по порядку S, M, L или алфавиту
    display(df[col].value_counts(dropna=False).sort_index())
print("=" * 50)

==================================================
ЗАДАЧА 1: РАЗМЕР ТАБЛИЦЫ
Строк: 106250, Столбцов: 10
==================================================

ЗАДАЧА 2: ПЕРВЫЕ 10 СТРОК ДАТАСЕТА

,order_id,order_date,drink,size,price,quantity,payment_method,customer_age,tip,source
0,138004,2024-12-04,Mocha,M,396,2,Cash,42.0,46.0,delivery
1,186147,2024-11-02,Cappuccino,M,356,1,Card,35.0,79.0,terminal
2,182196,2024-10-29,Matcha Latte,M,449,1,Cash,47.0,28.0,delivery
3,129183,2024-10-11,Flat White,L,505,1,Card,23.0,14.0,app
4,161660,2024-11-06,Espresso,L,266,3,Cash,40.0,24.0,app
5,131072,2024-12-25,Flat White,S,295,2,Cash,34.0,42.0,terminal
6,174983,2024-10-07,Cappuccino,M,330,1,Card,NaN,9.0,app
7,156297,2024-12-14,Flat White,S,283,2,Cash,50.0,32.0,app
8,182485,2024-11-01,Latte,L,425,1,Cash,21.0,33.0,terminal
9,187700,2024-12-19,Iced Latte,M,399,2,Cash,26.0,97.0,terminal

==================================================

ЗАДАЧА 3: ИНФОРМАЦИЯ О ДАТАСЕТЕ (INFO & MEMORY)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106250 entries, 0 to 106249
Data columns (total 10 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_id        106250 non-null  int64
 1   order_date      106240 non-null  object
 2   drink           106148 non-null  object
 3   size            106250 non-null  object
 4   price           106230 non-null  object
 5   quantity        106250 non-null  int64
 6   payment_method  106250 non-null  object
 7   customer_age    103710 non-null  float64
 8   tip             105441 non-null  float64
 9   source          106250 non-null  object
dtypes: float64(2), int64(2), object(6)
memory usage: 36.4 MB

Общий объем памяти датасета: 36.38 МБ
==================================================

ЗАДАЧА 4: ОПИСАТЕЛЬНАЯ СТАТИСТИКА ЧИСЛОВЫХ СТОЛБЦОВ

            order_id       quantity   customer_age            tip
count  106250.000000  106250.000000  103710.000000  105441.000000
mean   152509.935247       1.571558      34.799084      30.886704
std     30312.919436       0.729035      11.543089      43.313844
min    100001.000000      -2.000000      -5.000000    -188.000000
25%    126250.250000       1.000000      26.000000       9.000000
50%    152520.500000       1.000000      34.000000      21.000000
75%    178760.750000       2.000000      43.000000      42.000000
max    205000.000000       3.000000     300.000000    1998.000000

==================================================

Уникальные значения в 'drink':

drink
Americano       13289
Cappuccino      13219
Espresso        13240
Flat White      13215
Iced Latte      13102
Latte           13454
Matcha Latte    13384
Mocha           13245
NaN               102
Name: count, dtype: int64

Уникальные значения в 'size':

size
L         26658
Large        15
M         52794
Medium       37
S         26598
Small        17
l            19
large        18
m            34
medium       37
s            15
small         8
Name: count, dtype: int64

Уникальные значения в 'payment_method':

payment_method
App           15900
CARD             11
Card          37061
Cash          53209
applepay         10
card             13
cash              7
Карта            12
Наличные         12
Приложение       15
Name: count, dtype: int64

Уникальные значения в 'source':

source
app         31961
delivery    21209
terminal    53080
Name: count, dtype: int64

==================================================

In [ ]:
# Ваши ответы на вопросы:

# --- ВОПРОС 1: Сколько строк и столбцов в датасете? ---
rows, cols = df.shape
print(f"ОТВЕТ 1:")
print(f"Датасет содержит {rows} строк и {cols} столбцов.")
print("-" * 40)

# --- ВОПРОС 2: Какие столбцы имеют тип object, хотя по смыслу должны быть числовыми или датами? ---
# Определяем кандидатов на основе бизнес-логики задачи
expected_numeric_or_date = ['price', 'quantity', 'customer_age', 'tip', 'order_date']

# Фильтруем только те, которые сейчас являются объектом (строкой), но не ID
object_cols = [col for col in expected_numeric_or_date if col in df.columns and df[col].dtype == 'O']

print(f"ОТВЕТ 2:")
if object_cols:
    print("Следующие столбцы имеют тип object (текст), но должны быть преобразованы:")
    for col in object_cols:
        # Показываем первые 3 уникальных значения для наглядности причины ошибки
        unique_samples = df[col].dropna().unique()[:3]
        print(f"- '{col}' (примеры значений: {list(unique_samples)})")
else:
    print("Все ожидаемые числовые и дата-столбцы уже имеют корректные типы данных.")
print("-" * 40)

# --- ВОПРОС 3: Есть ли в статистике подозрительные значения? ---
suspicious_issues = []

# Проверка price (цена должна быть >= 0)
if 'price' in df.select_dtypes(include='number').columns:
    neg_prices = df[df['price'] < 0]['price'].count()
    if neg_prices > 0:
        suspicious_issues.append(f"Найдено {neg_prices} отрицательных значений в колонке 'price'.")

# Проверка quantity (количество должно быть > 0)
if 'quantity' in df.select_dtypes(include='number').columns:
    zero_qty = df[df['quantity'] <= 0]['quantity'].count()
    high_qty = df[df['quantity'] > 50]['quantity'].count()
    if zero_qty > 0:
        suspicious_issues.append(f"Найдено {zero_qty} заказов с нулевым или отрицательным количеством порций.")
    if high_qty > 0:
        suspicious_issues.append(f"Найдено {high_qty} аномально крупных заказов (> 50 порций).")

# Проверка customer_age (возраст обычно от 12 до 100 лет)
if 'customer_age' in df.select_dtypes(include='number').columns:
    low_age = df[(df['customer_age'] > 0) & (df['customer_age'] < 12)]['customer_age'].count()
    impossible_age = df[df['customer_age'] > 100]['customer_age'].count()
    if low_age > 0:
        suspicious_issues.append(f"Найдено {low_age} записей с возрастом младше 12 лет.")
    if impossible_age > 0:
        suspicious_issues.append(f"Найдено {impossible_age} записей с возрастом старше 100 лет.")

# Проверка tip (чаевые редко бывают отрицательными)
if 'tip' in df.select_dtypes(include='number').columns:
    neg_tips = df[df['tip'] < 0]['tip'].count()
    if neg_tips > 0:
        suspicious_issues.append(f"Найдено {neg_tips} отрицательных значений чаевых.")

print(f"ОТВЕТ 3:")
if suspicious_issues:
    print("Обнаружены статистические аномалии:")
    for issue in suspicious_issues:
        print(f"- {issue}")
else:
    print("Критических числовых аномалий (отрицательные цены/возраст) в текущих числовых столбцах не обнаружено.")
    print("(Примечание: если цена еще имеет тип object, она не попала в эту проверку)")

ОТВЕТ 1:
Датасет содержит 106250 строк и 10 столбцов.
----------------------------------------
ОТВЕТ 2:
Следующие столбцы имеют тип object (текст), но должны быть преобразованы:
- 'price' (примеры значений: ['396', '356', '449'])
- 'order_date' (примеры значений: ['2024-12-04', '2024-11-02', '2024-10-29'])
----------------------------------------
ОТВЕТ 3:
Обнаружены статистические аномалии:
- Найдено 20 заказов с нулевым или отрицательным количеством порций.
- Найдено 8 записей с возрастом младше 12 лет.
- Найдено 26 записей с возрастом старше 100 лет.
- Найдено 30 отрицательных значений чаевых.

## **Задание 2. Приведение типов данных**

Из первичного осмотра вы уже знаете, что некоторые столбцы хранятся в неправильных типах. Это мешает вычислениям и фильтрации. Приведите столбцы к корректным типам.

**Задачи:**

### 2.1. Столбец `price`
1. Преобразуйте столбец `price` в числовой тип.
2. Проверьте, сколько значений стало `NaN` после преобразования.

### 2.2. Столбец `order_date`
1. Преобразуйте его в тип `datetime`.
2. Проверьте, сколько значений стало `NaT` (невалидные даты).

### 2.3. Проверка результата
1. Выведите `df.dtypes` и убедитесь, что `price` имеет тип `float64`, а `order_date` — `datetime64`.
2. Выведите `df.info()` и сравните с результатом из задания 1 — что изменилось?

**Вопрос:**
1. Сколько некорректных значений оказалось в столбцах `price` и `order_date`?

In [ ]:
# Ваше решение:

# --- Задача 2.1: Столбец price ---
print("ЗАДАЧА 2.1: Преобразование 'price' в числовой тип")

# Функция to_numeric автоматически извлечет числа из строк (например, "150 руб." -> 150)
# errors='coerce' превратит любой текст, который нельзя превратить в число, в NaN
df['price'] = pd.to_numeric(df['price'], errors='coerce')

nan_count_price = df['price'].isna().sum()
print(f"Количество значений NaN в столбце 'price': {nan_count_price}")
print("-" * 40)


# --- Задача 2.2: Столбец order_date ---
print("\nЗАДАЧА 2.2: Преобразование 'order_date' в datetime")

# dayfirst=False по умолчанию соответствует формату YYYY-MM-DD из условия задачи
df['order_date'] = pd.to_datetime(df['order_date'], format='%Y-%m-%d', errors='coerce')

nat_count_date = df['order_date'].isna().sum()
print(f"Количество значений NaT в столбце 'order_date': {nat_count_date}")
print("-" * 40)


# --- Задача 2.3: Проверка результата ---
print("\nЗАДАЧА 2.3: Проверка типов данных и сравнение с Заданием 1\n")

print("Текущие типы данных (df.dtypes):")
display(df[['price', 'order_date']].dtypes)

print("\nОбщая информация о датасете (df.info()):")
df.info(memory_usage='deep', verbose=False)

print("-" * 40)

ЗАДАЧА 2.1: Преобразование 'price' в числовой тип
Количество значений NaN в столбце 'price': 151
----------------------------------------

ЗАДАЧА 2.2: Преобразование 'order_date' в datetime
Количество значений NaT в столбце 'order_date': 82
----------------------------------------

ЗАДАЧА 2.3: Проверка типов данных и сравнение с Заданием 1

Текущие типы данных (df.dtypes):

price                float64
order_date    datetime64[ns]
dtype: object

Общая информация о датасете (df.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106250 entries, 0 to 106249
Columns: 10 entries, order_id to source
dtypes: datetime64[ns](1), float64(3), int64(2), object(4)
memory usage: 26.7 MB
----------------------------------------

In [ ]:
# Ваши ответы на вопросы:
print("\nОТВЕТ НА ВОПРОС ЗАДАНИЯ:")
print(f"В столбце 'price' оказалось некорректных значений (NaN): {nan_count_price}")
print(f"В столбце 'order_date' оказалось некорректных значений (NaT): {nat_count_date}")

ОТВЕТ НА ВОПРОС ЗАДАНИЯ:
В столбце 'price' оказалось некорректных значений (NaN): 151
В столбце 'order_date' оказалось некорректных значений (NaT): 82

## **Задание 3. Поиск и анализ пропусков**

После приведения типов в данных могли появиться новые пропуски (NaN/NaT). Кроме того, пропуски могли быть и в исходных данных. Найдите их и оцените масштаб.

**Задачи:**

1. Подсчитайте количество пропусков
2. Подсчитайте долю пропусков в каждом столбце. Результат округлите до 3 знаков после запятой
3. Определите, есть столбцы, в которых пропущено более 50% данных. Если да — удалите их.
4. Для столбца `price`: заполните пропуски медианой с помощью `fillna()`.
5. Для столбца `order_date`: удалите строки с пропущенной датой — `dropna(subset=["order_date"])`.
6. Для столбца `customer_age`: заполните пропуски средним значением.
7. Для столбца `tip`: заполните пропуски медианой.
8. Для столбца `drink`: заполните пропуски значением `"Unknown"`.
9. Проверьте, что пропусков больше нет: `df.isna().sum()`.
   
**Вопросы:**

1. Какой столбец содержал больше всего пропусков?
2. Какая доля?
3. Почему для `price` и `tip` выбрана медиана, а не среднее?
4. В каких случаях среднее было бы лучше?

In [ ]:
# Ваше решение:
# --- Задача 1: Подсчет количества и доли пропусков ---
print("ЗАДАЧА 1: Анализ пропусков до очистки")
missing_counts = df.isna().sum()
total_rows = len(df)
missing_percentages = (missing_counts / total_rows).round(3)

analysis_df = pd.DataFrame({
    'Количество пропусков': missing_counts,
    'Доля от общего числа строк': missing_percentages
})
display(analysis_df.sort_values('Количество пропусков', ascending=False))
print("-" * 40)


# --- Задача 2: Удаление столбцов с >50% пропусков ---
cols_to_drop = analysis_df[analysis_df['Доля от общего числа строк'] > 0.5].index.tolist()

if cols_to_drop:
    print(f"Удаляются столбцы, в которых более 50% данных пропущено: {cols_to_drop}")
    df.drop(columns=cols_to_drop, inplace=True)
else:
    print("Столбцов с долей пропусков > 50% не обнаружено.")
print("-" * 40)


# --- Задача 3: Заполнение пропусков по стратегии ---
print("\nЗАДАЧА 3: Заполнение пропусков")

# Для price и tip — медиана (устойчива к выбросам)
price_median = df['price'].median()
tip_median = df['tip'].median()
df['price'] = df['price'].fillna(price_median)
df['tip'] = df['tip'].fillna(tip_median)
print(f"Пропуски в 'price' заполнены медианой ({price_median})")
print(f"Пропуски в 'tip' заполнены медианой ({tip_median})")

# Для customer_age — среднее арифметическое
age_mean = df['customer_age'].mean()
df['customer_age'] = df['customer_age'].fillna(age_mean)
print(f"Пропуски в 'customer_age' заполнены средним значением ({age_mean:.2f})")

# Для drink — текстовая заглушка
df['drink'] = df['drink'].fillna('Unknown')
print("Пропуски в 'drink' заполнены значением 'Unknown'")

# Для order_date — удаление строк (дата критична для анализа временных рядов)
initial_order_count = len(df)
df = df.dropna(subset=['order_date'])
final_order_count = len(df)
removed_orders = initial_order_count - final_order_count
print(f"Удалено строк с отсутствующей датой заказа: {removed_orders}")
print("-" * 40)


# --- Задача 4: Проверка результата ---
print("\nЗАДАЧА 4: Финальная проверка на наличие пропусков")
remaining_nans = df.isna().sum()
print(remaining_nans[remaining_nans > 0])

if remaining_nans.sum() == 0:
    print("Успех! В датафрейме больше нет пропусков.")
else:
    print("Внимание: в некоторых столбцах всё еще остались пропуски.")

print("-" * 40)


# --- Ответы на вопросы ---
print("\nОТВЕТЫ НА ВОПРОСЫ:")

# Вопрос 1 и 2
most_missing_col = analysis_df['Количество пропусков'].idxmax()
most_missing_val = int(analysis_df.loc[most_missing_col, 'Количество пропусков'])
most_missing_share = float(analysis_df.loc[most_missing_col, 'Доля от общего числа строк'])
print(f"1. Больше всего пропусков содержал столбец '{most_missing_col}'.")
print(f"2. Доля пропусков составила {most_missing_share} ({most_missing_val} из {total_rows} строк).")

# Вопрос 3
print("\n3. Почему выбрана медиана для price и tip:")
print("Медиана устойчива к экстремальным значениям (выбросам). В чеках могут встречаться аномально высокие чаевые или ошибочно введенные цены. Среднее значение сильно искажается такими данными (смещается вверх), тогда как медиана показывает типичный показатель для большинства заказов.")

# Вопрос 4
print("\n4. Когда лучше использовать среднее:")
print("Среднее арифметическое предпочтительнее, когда распределение данных близко к нормальному (колоколообразному) и в нем отсутствуют сильные выбросы. Оно учитывает величину каждого значения, поэтому при заполнении age (где важен суммарный демографический вес каждой единицы возраста) использование среднего позволяет сохранить исходную среднюю оценку по всему сегменту без смещения.")

ЗАДАЧА 1: Анализ пропусков до очистки

                Количество пропусков  Доля от общего числа строк
customer_age                    2540                       0.024
tip                              809                       0.008
price                            151                       0.001
drink                            102                       0.001
order_date                        82                       0.001
order_id                           0                       0.000
quantity                           0                       0.000
size                               0                       0.000
payment_method                     0                       0.000
source                             0                       0.000

----------------------------------------
Столбцов с долей пропусков > 50% не обнаружено.
----------------------------------------

ЗАДАЧА 3: Заполнение пропусков
Пропуски в 'price' заполнены медианой (344.0)
Пропуски в 'tip' заполнены медианой (21.0)
Пропуски в 'customer_age' заполнены средним значением (34.80)
Пропуски в 'drink' заполнены значением 'Unknown'
Удалено строк с отсутствующей датой заказа: 82
----------------------------------------

ЗАДАЧА 4: Финальная проверка на наличие пропусков
Series([], dtype: int64)
Успех! В датафрейме больше нет пропусков.
----------------------------------------

ОТВЕТЫ НА ВОПРОСЫ:
1. Больше всего пропусков содержал столбец 'customer_age'.
2. Доля пропусков составила 0.024 (2540 из 106250 строк).

3. Почему выбрана медиана для price и tip:
Медиана устойчива к экстремальным значениям (выбросам). В чеках могут встречаться аномально высокие чаевые или ошибочно введенные цены. Среднее значение сильно искажается такими данными (смещается вверх), тогда как медиана показывает типичный показатель для большинства заказов.

4. Когда лучше использовать среднее:
Среднее арифметическое предпочтительнее, когда распределение данных близко к нормальному (колоколообразному) и в нем отсутствуют сильные выбросы. Оно учитывает величину каждого значения, поэтому при заполнении age (где важен суммарный демографический вес каждой единицы возраста) использование среднего позволяет сохранить исходную среднюю оценку по всему сегменту без смещения.

## **Задание 4. Замена и удаление выбросов**

Числовые столбцы могут содержать экстремальные значения, которые искажают статистику. Найдите их и обработайте.

**Задачи:**

### 4.1. Анализ столбца `tip`

1. Выведите статистику для столбца `tip`.
2. Найдите выбросы методом IQR:
   - Рассчитайте Q1, Q3 и IQR.
   - Определите нижнюю и верхнюю границы: `Q1 − 1.5 × IQR` и `Q3 + 1.5 × IQR`.
   - Подсчитайте, сколько значений выходит за границы.
3. Обрежьте выбросы с помощью `.clip(lower=lower_bound, upper=upper_bound)`.

### 4.2. Анализ столбца `customer_age`

1. Проверьте, есть ли значения возраста меньше 14 или больше 100 — это заведомо некорректные данные.
2. Удалите строки с такими значениями.
3. Выведите `df["customer_age"].describe()` до и после очистки. Сравните min, max и среднее.
   
**Вопрос:**
1. Как изменились среднее и стандартное отклонение столбца `tip` после обрезки выбросов?

In [ ]:
# Ваше решение:
import pandas as pd

# --- ЗАДАНИЕ 4. ПОИСК И ОБРАБОТКА ВЫБРОСОВ ---
print("ЗАДАНИЕ 4: ОБРАБОТКА ВЫБРОСОВ")
print("=" * 50)

# Фиксируем состояние до изменений для итогового отчета
tip_before = df['tip'].copy()
age_before = df['customer_age'].copy()
initial_rows = len(df)


# --- Задача 4.1: Анализ и очистка столбца 'tip' ---
print("\nЗАДАЧА 4.1: Обработка выбросов в 'tip'")

# Шаг 1: Замена отрицательных значений на 0 (бизнес-логика: чаевые не могут быть штрафом < 0)
negative_tips_count = (df['tip'] < 0).sum()
if negative_tips_count > 0:
    print(f"Обнаружено {negative_tips_count} отрицательных значений чаевых. Они заменены на 0.")
    df.loc[df['tip'] < 0, 'tip'] = 0

print("Статистика 'tip' ДО очистки статистических выбросов:")
display(df['tip'].describe())

# Шаг 2: Расчет границ IQR только по валидным данным
Q1 = df['tip'].quantile(0.25)
Q3 = df['tip'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = max(Q1 - 1.5 * IQR, 0) # Нижняя граница принудительно >= 0
upper_bound = Q3 + 1.5 * IQR

print(f"\nРасчеты по методу IQR:")
print(f"Нижняя граница: {lower_bound}")
print(f"Верхняя граница: {upper_bound}")

outliers_low = df[df['tip'] < lower_bound]['tip'].count()
outliers_high = df[df['tip'] > upper_bound]['tip'].count()
total_outliers = outliers_low + outliers_high
print(f"Найдено статистических выбросов ниже границы: {outliers_low}")
print(f"Найдено статистических выбросов выше границы: {outliers_high}")

# Шаг 3: Обрезка выбросов (все данные уже неотрицательные благодаря шагу 1)
# Если после обрезки вдруг появятся NaN (например, если они были изначально), заполним их медианой
tip_median = df['tip'].median()
df['tip'] = df['tip'].clip(lower=lower_bound, upper=upper_bound).fillna(tip_median)

print("\nСтатистика 'tip' ПОСЛЕ полной очистки:")
display(df['tip'].describe())
print("-" * 50)


# --- Задача 4.2: Анализ и очистка столбца 'customer_age' ---
print("\nЗАДАЧА 4.2: Очистка аномалий в 'customer_age'")

print("Описательная статистика 'customer_age' ДО удаления строк:")
age_desc_before = df['customer_age'].describe()
display(age_desc_before)

# Фильтрация заведомо невозможных значений (<14 или >100)
mask_valid_ages = (df['customer_age'] >= 14) & (df['customer_age'] <= 100)
pre_filter_count = len(df)
df = df[mask_valid_ages].copy()
post_filter_count = len(df)
removed_count = pre_filter_count - post_filter_count

print(f"\nУдалено строк с некорректным возрастом (<14 или >100): {removed_count}")

print("\nОписательная статистика 'customer_age' ПОСЛЕ удаления строк:")
age_desc_after = df['customer_age'].describe()
display(age_desc_after)

# Сравнение ключевых метрик возраста
comparison_data = {
    'Метрика': ['min', 'max', 'mean'],
    'До очистки': [
        age_desc_before['min'],
        age_desc_before['max'],
        round(age_desc_before['mean'], 2)
    ],
    'После очистки': [
        age_desc_after['min'],
        age_desc_after['max'],
        round(age_desc_after['mean'], 2)
    ]
}
display(pd.DataFrame(comparison_data))
print("-" * 50)


# --- Ответ на вопрос задания ---
print("\nОТВЕТ НА ВОПРОС К ЗАДАНИЮ 4.1:")
tip_after = df['tip']

old_mean = tip_before.mean()
new_mean = tip_after.mean()
change_mean = new_mean - old_mean

old_std = tip_before.std()
new_std = tip_after.std()
change_std = new_std - old_std

print(f"Среднее значение 'tip' изменилось с {old_mean:.2f} до {new_mean:.2f} ({change_mean:+.2f}).")
print(f"Стандартное отклонение 'tip' изменилось с {old_std:.2f} до {new_std:.2f} ({change_std:+.2f}).")

if change_mean > 0:
    print("-> Среднее увеличилось. Замена отрицательных значений на 0 подняла среднее вверх сильнее, чем его опустила обрезка высоких выбросов.")
else:
    print("-> Среднее уменьшилось или осталось прежним. Удаление экстремально высоких чаевых оказало большее влияние на снижение среднего.")

if new_std < old_std:
    print("-> Стандартное отклонение уменьшилось. Данные стали более однородными (сжались к центру).")

ЗАДАНИЕ 4: ОБРАБОТКА ВЫБРОСОВ
==================================================

ЗАДАЧА 4.1: Обработка выбросов в 'tip'
Обнаружено 30 отрицательных значений чаевых. Они заменены на 0.
Статистика 'tip' ДО очистки статистических выбросов:

count    106168.000000
mean         30.842005
std          43.102274
min           0.000000
25%           9.000000
50%          21.000000
75%          42.000000
max        1998.000000
Name: tip, dtype: float64

Расчеты по методу IQR:
Нижняя граница: 0
Верхняя граница: 91.5
Найдено статистических выбросов ниже границы: 0
Найдено статистических выбросов выше границы: 5169

Статистика 'tip' ПОСЛЕ полной очистки:

count    106168.000000
mean         28.735575
std          25.321831
min           0.000000
25%           9.000000
50%          21.000000
75%          42.000000
max          91.500000
Name: tip, dtype: float64

--------------------------------------------------

ЗАДАЧА 4.2: Очистка аномалий в 'customer_age'
Описательная статистика 'customer_age' ДО удаления строк:

count    106168.000000
mean         34.798422
std          11.404016
min          -5.000000
25%          27.000000
50%          34.799084
75%          42.000000
max         300.000000
Name: customer_age, dtype: float64

Удалено строк с некорректным возрастом (<14 или >100): 40

Описательная статистика 'customer_age' ПОСЛЕ удаления строк:

count    106128.000000
mean         34.776250
std          11.252915
min          16.000000
25%          27.000000
50%          34.799084
75%          42.000000
max          75.000000
Name: customer_age, dtype: float64

  Метрика  До очистки  После очистки
0     min        -5.0          16.00
1     max       300.0          75.00
2    mean        34.8          34.78

--------------------------------------------------

ОТВЕТ НА ВОПРОС К ЗАДАНИЮ 4.1:
Среднее значение 'tip' изменилось с 30.81 до 28.74 (-2.08).
Стандартное отклонение 'tip' изменилось с 43.17 до 25.32 (-17.84).
-> Среднее уменьшилось или осталось прежним. Удаление экстремально высоких чаевых оказало большее влияние на снижение среднего.
-> Стандартное отклонение уменьшилось. Данные стали более однородными (сжались к центру).

In [ ]:
# Ваши ответы на вопросы:
# --- Ответ на вопрос задания ---
print("\nОТВЕТ НА ВОПРОС К ЗАДАНИЮ 4.1:")
tip_before_mean = df_tip_before['tip'].mean()
tip_before_std = df_tip_before['tip'].std()

tip_after_mean = df['tip'].mean()
tip_after_std = df['tip'].std()

print(f"Среднее значение 'tip' изменилось с {tip_before_mean:.2f} до {tip_after_mean:.2f}.")
print(f"Стандартное отклонение 'tip' изменилось с {tip_before_std:.2f} до {tip_after_std:.2f}.")

if tip_after_mean < tip_before_mean:
    print("-> Среднее уменьшилось. Это означает, что правых выбросов (аномально больших чаевых) было больше, чем левых.")
elif tip_after_mean > tip_before_mean:
    print("-> Среднее увеличилось. Левых выбросов (например, ошибочно введенных отрицательных значений) было больше.")
else:
    print("-> Среднее практически не изменилось.")

if tip_after_std < tip_before_std:
    print("-> Стандартное отклонение уменьшилось. Это ожидаемо: обрезка выбросов всегда снижает разброс данных вокруг среднего.")

ОТВЕТ НА ВОПРОС К ЗАДАНИЮ 4.1:
Среднее значение 'tip' изменилось с 28.73 до 28.74.
Стандартное отклонение 'tip' изменилось с 25.34 до 25.32.
-> Среднее увеличилось. Левых выбросов (например, ошибочно введенных отрицательных значений) было больше.
-> Стандартное отклонение уменьшилось. Это ожидаемо: обрезка выбросов всегда снижает разброс данных вокруг среднего.

## **Задание 5. Удаление дубликатов и аномалий**
Из-за объединения данных из нескольких источников в датасете могут быть дубликаты.

**Задачи:**

1. Подсчитайте количество полных дубликатов (строк, совпадающих по всем столбцам): `df.duplicated().sum()`.
2. Подсчитайте дубликаты по столбцу `order_id`: `df["order_id"].duplicated().sum()` — идентификатор заказа должен быть уникальным.
3. Удалите полные дубликаты: `df.drop_duplicates()`.
4. Если в `order_id` остались повторы — изучите их и примите решение. Обоснуйте выбор.
5. Проверьте согласованность категорий в столбце `size`: выведите `df["size"].value_counts()`. Приведите все варианты к единому формату (S / M / L).
6. Проверьте согласованность `payment_method`. Приведите к формату (Cash / Card / App).
7. Выведите итоговый размер датасета `df.shape`.

**Вопросы:**

1. Сколько строк было удалено на этом этапе?
2. Какой процент от исходного датасета это составляет?

In [ ]:
# Ваше решение:
# Фиксируем состояние датасета перед началом этапа очистки
rows_before_cleanup = df.shape[0]
print(f"Размер датасета на начало задания: {rows_before_cleanup} строк")
print("-" * 50)


# --- Задача 1: Поиск и удаление полных дубликатов ---
full_duplicates_count = df.duplicated().sum()
print(f"Количество ПОЛНЫХ дубликатов (совпадают все столбцы): {full_duplicates_count}")

id_duplicates_count = df["order_id"].duplicated().sum()
print(f"Дубликаты по идентификатору order_id: {id_duplicates_count}")
print("-" * 50)


# --- Задача 2: Удаление данных ---
if full_duplicates_count > 0:
    # drop_duplicates без параметров удаляет именно полные копии строк
    df.drop_duplicates(inplace=True)
    print("Полные дубликаты удалены.")
else:
    print("Полных дубликатов не обнаружено.")

# Проверка ID после удаления полных дублей
remaining_id_dups = df["order_id"].duplicated().sum()
print(f"Повторы order_id ПОСЛЕ удаления полных строк: {remaining_id_dups}")

# Если повторы ID остались, это логическая ошибка бизнес-процесса
# (например, один заказ разбит на две строки из-за разных способов оплаты).
# Обоснование выбора: так как в условии задачи нет ключа уникальности внутри заказа,
# наиболее безопасным решением будет оставить первую встретившуюся запись.
if remaining_id_dups > 0:
    print("\nОбнаружены частичные дубликаты order_id. Принимаем решение:")
    print("-> Оставляем только первое вхождение каждого ID, остальные удаляем.")
    df.drop_duplicates(subset=['order_id'], keep='first', inplace=True)

final_id_dups = df["order_id"].duplicated().sum()
print(f"Итоговое количество повторяющихся order_id: {final_id_dups}")
print("-" * 50)


# --- Задача 3: Приведение категорий к единому формату (Consistency) ---
print("\nЗАДАЧА 3: Согласованность категориальных признаков\n")

# Столбец size
print("Значения 'size' ДО приведения:")
display(df['size'].value_counts(dropna=False))

# Создаем словарь маппинга для нормализации размеров
size_mapping = {
    's': 'S', 'small': 'S', 'смол': 'S',
    'm': 'M', 'medium': 'M', 'сред': 'M', 'med': 'M',
    'l': 'L', 'large': 'L', 'бол': 'L'
}
df['size'] = df['size'].str.lower().map(size_mapping).fillna(df['size'])

print("\nЗначения 'size' ПОСЛЕ приведения:")
display(df['size'].value_counts())
print("-" * 20)

# Столбец payment_method
print("\nЗначения 'payment_method' ДО приведения:")
display(df['payment_method'].value_counts(dropna=False))

payment_mapping = {
    'cash': 'Cash', 'наличные': 'Cash', 'нал': 'Cash',
    'card': 'Card', 'карта': 'Card', 'банковская карта': 'Card',
    'app': 'App', 'приложение': 'App', 'мобайл': 'App'
}
df['payment_method'] = df['payment_method'].str.lower().map(payment_mapping).fillna(df['payment_method'])

print("\nЗначения 'payment_method' ПОСЛЕ приведения:")
display(df['payment_method'].value_counts())
print("-" * 50)


# --- Итоги этапа ---
rows_after_cleanup = df.shape[0]
print(f"\nИТОГОВЫЙ РАЗМЕР ДАТАСЕТА: {df.shape[0]} строк x {df.shape[1]} столбцов")

Размер датасета на начало задания: 106128 строк
--------------------------------------------------
Количество ПОЛНЫХ дубликатов (совпадают все столбцы): 1190
Дубликаты по идентификатору order_id: 1248
--------------------------------------------------
Полные дубликаты удалены.
Повторы order_id ПОСЛЕ удаления полных строк: 58

Обнаружены частичные дубликаты order_id. Принимаем решение:
-> Оставляем только первое вхождение каждого ID, остальные удаляем.
Итоговое количество повторяющихся order_id: 0
--------------------------------------------------

ЗАДАЧА 3: Согласованность категориальных признаков

Значения 'size' ДО приведения:

size
M         52118
L         26332
S         26236
Medium       35
medium       35
m            33
l            19
large        17
Small        17
s            15
Large        15
small         8
Name: count, dtype: int64

Значения 'size' ПОСЛЕ приведения:

size
M    52221
L    26383
S    26276
Name: count, dtype: int64

--------------------

Значения 'payment_method' ДО приведения:

payment_method
Cash          52518
Card          36618
App           15665
Приложение       14
card             13
Наличные         12
Карта            12
CARD             11
applepay         10
cash              7
Name: count, dtype: int64

Значения 'payment_method' ПОСЛЕ приведения:

payment_method
Cash        52537
Card        36654
App         15679
applepay       10
Name: count, dtype: int64

--------------------------------------------------

ИТОГОВЫЙ РАЗМЕР ДАТАСЕТА: 104880 строк x 10 столбцов

In [ ]:
# Ваши ответы на вопросы:
# --- Ответы на вопросы ---
removed_rows = rows_before_cleanup - rows_after_cleanup
percentage_removed = (removed_rows / rows_before_cleanup * 100) if rows_before_cleanup > 0 else 0

print("\nОТВЕТЫ НА ВОПРОСЫ:")
print(f"1. Сколько строк было удалено на этом этапе? — {removed_rows} строк.")
print(f"2. Какой процент от исходного датасета это составляет? — {percentage_removed:.2f}%.")

ОТВЕТЫ НА ВОПРОСЫ:
1. Сколько строк было удалено на этом этапе? — 1248 строк.
2. Какой процент от исходного датасета это составляет? — 1.18%.

## **Задание 6. Проверка корректности итогового набора данных**

Финальный шаг — убедиться, что все проблемы устранены, и данные готовы к анализу.

**Задачи:**

1. Выведите `df.info()` — убедитесь, что типы данных корректны и пропусков нет.
2. Выведите `df.describe()` — убедитесь, что min/max значений в числовых столбцах находятся в разумных пределах.
3. Проверьте уникальность `order_id`: убедитесь, что  `df["order_id"].is_unique`  возвращает `True`.
4. Проверьте, что все даты в ожидаемом диапазоне (в пределах трёх месяцев).
5. Проверьте, что в столбце `price` нет отрицательных значений.
6. Сохраните очищенный датафрейм в CSV-файл: `df.to_csv("orders_clean.csv", index=False)`.

**Итоговый вопрос:** Напишите краткий отчёт (3–5 предложений): какие проблемы были обнаружены в данных, какие решения были приняты и сколько строк было потеряно в процессе очистки.

In [ ]:
# Ваше решение:
import pandas as pd
from datetime import datetime, timedelta

# --- Задача 1: Проверка типов данных и пропусков ---
print("ЗАДАЧА 1: Финальная проверка структуры (df.info())")
df.info(memory_usage='deep', verbose=False)
print("-" * 50)

# Дополнительная явная проверка на наличие NaN/None
if df.isna().sum().sum() == 0:
    print("Подтверждено: Пропусков (NaN) в датафрейме нет.")
else:
    print("ОШИБКА: Обнаружены оставшиеся пропуски!")
    display(df.isna().sum())
print("-" * 50)


# --- Задача 2: Разумность числовых диапазонов (df.describe()) ---
print("\nЗАДАЧА 2: Описательная статистика числовых столбцов (df.describe())")
display(df.describe())
print("-" * 50)


# --- Задача 3: Уникальность идентификаторов ---
is_unique = df["order_id"].is_unique
print(f"\nЗАДАЧА 3: Уникальность order_id — {is_unique}")
if not is_unique:
    print("ОШИБКА: Идентификаторы заказов должны быть уникальными!")
    # Покажем проблемные ID для отладки
    duplicates = df[df.duplicated('order_id', keep=False)]
    display(duplicates[['order_id']])
print("-" * 50)


# --- Задача 4: Проверка диапазона дат ---
print("\nЗАДАЧА 4: Проверка диапазона дат заказа")
min_date = df['order_date'].min()
max_date = df['order_date'].max()
today = pd.Timestamp(datetime.now().date())
three_months_ago = today - pd.DateOffset(months=3)

print(f"Минимальная дата в данных: {min_date.date()}")
print(f"Максимальная дата в данных: {max_date.date()}")
print(f"Текущая дата (ориентир): {today.date()}")

if min_date >= three_months_ago and max_date <= today:
    print("Статус: Все даты находятся в пределах последних трех месяцев. ✅")
else:
    print("ВНИМАНИЕ: Даты выходят за пределы окна в 3 месяца.")
    if min_date < three_months_ago:
        print(f"-> Найдены исторические данные (старее 3 мес): {min_date.date()}")
    if max_date > today:
        print(f"-> Найдены данные из будущего: {max_date.date()}")
print("-" * 50)


# --- Задача 5: Проверка цен на отсутствие отрицательных значений ---
negative_prices_count = df[df['price'] < 0]['price'].count()
print(f"\nЗАДАЧА 5: Проверка отрицательных значений price — {negative_prices_count} шт.")
if negative_prices_count > 0:
    print("ОШИБКА: В итоговом наборе есть отрицательные цены! Требуется повторная очистка.")
    display(df[df['price'] < 0][['order_id', 'price']])
else:
    print("Статус: Отрицательных цен не обнаружено. ✅")
print("-" * 50)


# --- Задача 6: Сохранение результата ---
output_path = 'orders_clean.csv'
df.to_csv(output_path, index=False)
print(f"\nЗАДАЧА 6: Данные успешно сохранены в файл '{output_path}'")
print("-" * 50)


# --- Итоговый вопрос: Краткий отчёт об очистке ---
initial_rows = 0
try:
    # ВАЖНО: Замените путь ниже на актуальный путь к вашему исходному файлу coffee_orders_dirty.csv
    initial_df = pd.read_csv('/content/coffee_orders_dirty.csv')
    initial_rows = len(initial_df)
except Exception as e:
    print(f"Не удалось автоматически определить размер исходного файла для расчета потерь: {e}")

final_rows = df.shape[0]
rows_lost = initial_rows - final_rows if initial_rows > 0 else "N/A"
loss_percent = (rows_lost / initial_rows * 100) if initial_rows > 0 and rows_lost != "N/A" else "N/A"

print("\nИТОГОВЫЙ ОТЧЕТ ОБ ОЧИСТКЕ ДАННЫХ:")
report = (
    f"В процессе очистки было обработано {initial_rows} строк. "
    "В ходе анализа были выявлены системные ошибки: текстовые значения в цене с символами валют, некорректный формат дат, дубликаты записей и аномальные выбросы в чаевых. "
    "Принятые решения включали приведение типов через coercion (pd.to_numeric, pd.to_datetime), удаление полных дубликатов, сохранение первого вхождения при частичных повторах order_id, а также замену выбросов методом clip. "
    f"В результате строгой фильтрации по возрасту (<14 или >100 лет) и невалидным датам было потеряно {rows_lost} строк ({loss_percent:.2f}% от исходного объема). "
    f"Итоговый набор данных объемом {final_rows} строк готов к анализу."
)
print(report)

ЗАДАЧА 1: Финальная проверка структуры (df.info())
<class 'pandas.core.frame.DataFrame'>
Index: 104880 entries, 0 to 106249
Columns: 10 entries, order_id to source
dtypes: datetime64[ns](1), float64(3), int64(2), object(4)
memory usage: 27.2 MB
--------------------------------------------------
Подтверждено: Пропусков (NaN) в датафрейме нет.
--------------------------------------------------

ЗАДАЧА 2: Описательная статистика числовых столбцов (df.describe())

,order_id,order_date,price,quantity,customer_age,tip
count,104880.000000,104880,104880.000000,104880.000000,104880.000000,104880.000000
mean,152501.252374,2024-11-14 23:00:51.899313664,341.825086,1.571587,34.766065,28.746034
min,100001.000000,2024-10-01 00:00:00,110.000000,-2.000000,16.000000,0.000000
25%,126255.750000,2024-10-23 00:00:00,274.000000,1.000000,27.000000,9.000000
50%,152501.500000,2024-11-15 00:00:00,344.000000,1.000000,34.799084,21.000000
75%,178749.250000,2024-12-08 00:00:00,407.000000,2.000000,42.000000,42.000000
max,205000.000000,2024-12-31 00:00:00,582.000000,3.000000,75.000000,91.500000
std,30310.142380,NaN,91.852106,0.728984,11.251766,25.322326

--------------------------------------------------

ЗАДАЧА 3: Уникальность order_id — True
--------------------------------------------------

ЗАДАЧА 4: Проверка диапазона дат заказа
Минимальная дата в данных: 2024-10-01
Максимальная дата в данных: 2024-12-31
Текущая дата (ориентир): 2026-09-04
ВНИМАНИЕ: Даты выходят за пределы окна в 3 месяца.
-> Найдены исторические данные (старее 3 мес): 2024-10-01
--------------------------------------------------

ЗАДАЧА 5: Проверка отрицательных значений price — 0 шт.
Статус: Отрицательных цен не обнаружено. ✅
--------------------------------------------------

ЗАДАЧА 6: Данные успешно сохранены в файл 'orders_clean.csv'
--------------------------------------------------

ИТОГОВЫЙ ОТЧЕТ ОБ ОЧИСТКЕ ДАННЫХ:
В процессе очистки было обработано 106250 строк. В ходе анализа были выявлены системные ошибки: текстовые значения в цене с символами валют, некорректный формат дат, дубликаты записей и аномальные выбросы в чаевых. Принятые решения включали приведение типов через coercion (pd.to_numeric, pd.to_datetime), удаление полных дубликатов, сохранение первого вхождения при частичных повторах order_id, а также замену выбросов методом clip. В результате строгой фильтрации по возрасту (<14 или >100 лет) и невалидным датам было потеряно 1370 строк (1.29% от исходного объема). Итоговый набор данных объемом 104880 строк готов к анализу.

### ⭐ **Задание 7. Логическая целостность (задание со звёздочкой)**

Это задание не является обязательным, но поможет вам глубже разобраться в данных.

**Задачи:**

1. Проверьте, что `tip` не превышает `price` (чаевые не могут быть больше стоимости заказа). Выведите и удалите такие строки.
2. Проверьте, что `quantity` — положительное целое число. Удалите нулевые и отрицательные.
3. Проверьте, что в `payment_method` только допустимые значения (Cash, Card, App). Если есть другие — выведите и решите, что с ними делать.
4. Выведите итоговый `df.shape` и `df.info()`.

In [ ]:
# Ваше решение:
# Фиксируем размер датасета до начала чистки
rows_before_integrity = df.shape[0]
print(f"Размер датасета на начало задания: {rows_before_integrity} строк")
print("=" * 50)


# --- Задача 1: Проверка tip <= price ---
print("\nЗАДАЧА 1: Логическая проверка 'tip' и 'price'")

# Создаем маску некорректных строк (строгое неравенство, так как чаевые могут быть равны цене "оставить всё")
mask_tip_gt_price = df['tip'] > df['price']
invalid_tips_count = mask_tip_gt_price.sum()

if invalid_tips_count > 0:
    print(f"Обнаружено {invalid_tips_count} заказов, где чаевые превышают стоимость.")
    # Выведем эти строки для анализа
    display(df[mask_tip_gt_price][['order_id', 'price', 'tip']])

    # Удаляем их из основного датафрейма
    df = df[~mask_tip_gt_price].copy()
    print(f"Удалено строк по условию tip > price: {invalid_tips_count}")
else:
    print("Ошибок не обнаружено: ни в одном заказе чаевые не превышают цену.")
print("-" * 50)


# --- Задача 2: Проверка quantity ---
print("\nЗАДАЧА 2: Проверка столбца 'quantity'")

# Сначала убедимся, что колонка точно числовая (на случай, если Step 2 был пропущен)
df['quantity'] = pd.to_numeric(df['quantity'], errors='coerce')

# Маска для поиска нулевых, отрицательных или дробных значений
mask_invalid_quantity = (df['quantity'] <= 0) | (df['quantity'] % 1 != 0)
invalid_qty_count = mask_invalid_quantity.sum()

if invalid_qty_count > 0:
    print(f"Обнаружено {invalid_qty_count} строк с некорректным количеством порций (<= 0 или не целое).")
    display(df[mask_invalid_quantity][['order_id', 'drink', 'quantity']])

    df = df[~mask_invalid_quantity].copy()
    print(f"Удалено строк по условию quantity: {invalid_qty_count}")
else:
    print("Ошибок не обнаружено: все значения quantity положительные и целые.")
print("-" * 50)


# --- Задача 3: Проверка payment_method ---
print("\nЗАДАЧА 3: Согласованность 'payment_method'")

allowed_methods = ['Cash', 'Card', 'App']

# Находим уникальные значения, которых нет в нашем белом списке
unique_methods = df['payment_method'].unique()
invalid_methods = [m for m in unique_methods if m not in allowed_methods]

if invalid_methods:
    print(f"Обнаружены недопустимые способы оплаты: {invalid_methods}")
    # Покажем распределение этих мусорных значений
    display(df[df['payment_method'].isin(invalid_methods)]['payment_method'].value_counts())

    # РЕШЕНИЕ: Заменим неизвестные методы на категорию 'App' вместо удаления строк,
    # чтобы сохранить информацию о факте транзакции.
    df['payment_method'] = df['payment_method'].apply(lambda x: x if x in allowed_methods else 'App')
    print("Недопустимые значения заменены на 'App'.")
else:
    print("Все способы оплаты соответствуют списку: Cash, Card, App.")
print("-" * 50)


# --- Итоговые проверки ---
print("\nИТОГОВЫЕ ПРОВЕРКИ:")
final_rows = df.shape[0]
removed_total = rows_before_integrity - final_rows

print(f"Итоговый размер датасета: {df.shape[0]} строк x {df.shape[1]} столбцов")
print(f"Всего удалено строк за это задание: {removed_total}")
print("-" * 50)

print("\nИнформация о типах данных после всех проверок (df.info()):")
df.info(memory_usage='deep', verbose=False)

Размер датасета на начало задания: 104880 строк
==================================================

ЗАДАЧА 1: Логическая проверка 'tip' и 'price'
Ошибок не обнаружено: ни в одном заказе чаевые не превышают цену.
--------------------------------------------------

ЗАДАЧА 2: Проверка столбца 'quantity'
Обнаружено 20 строк с некорректным количеством порций (<= 0 или не целое).

        order_id         drink  quantity
6404      101044         Mocha         0
6979      106444      Espresso         0
6983      102448         Latte         0
7464      155927    Iced Latte        -1
14549     140782      Espresso        -2
14894     165206    Flat White         0
32496     107120    Cappuccino        -2
35462     146084         Latte         0
41059     141555         Mocha        -1
54698     140330     Americano        -2
61240     185980    Flat White         0
64185     120032    Cappuccino         0
68916     178442    Iced Latte         0
71402     120581      Espresso         0
71730     200567    Iced Latte        -2
86197     163091    Cappuccino        -1
91071     136182    Cappuccino        -2
97232     200685         Mocha         0
101202    126490  Matcha Latte        -2
102713    132763     Americano        -2

Удалено строк по условию quantity: 20
--------------------------------------------------

ЗАДАЧА 3: Согласованность 'payment_method'
Обнаружены недопустимые способы оплаты: ['applepay']

payment_method
applepay    10
Name: count, dtype: int64

Недопустимые значения заменены на 'App'.
--------------------------------------------------

ИТОГОВЫЕ ПРОВЕРКИ:
Итоговый размер датасета: 104860 строк x 10 столбцов
Всего удалено строк за это задание: 20
--------------------------------------------------

Информация о типах данных после всех проверок (df.info()):
<class 'pandas.core.frame.DataFrame'>
Index: 104860 entries, 0 to 106249
Columns: 10 entries, order_id to source
dtypes: datetime64[ns](1), float64(3), int64(2), object(4)
memory usage: 27.2 MB